package it.unipi.DSL
class defs{
    final String rtt_calculation = "rtt_calculation"
    final String avg_ping = "avg_ping"
    final String traceroute_list = "traceroute_list"
    final String one_off = "one_off"
    final String max = "max"
    final String min = "min"
    final String start = "start"
    final String stop = "stop"
    final String measurements = "measurements"
    final String probes = "probes"
    final String anchors = "anchors"
    final String results = "results"
    final String hop = "hop"
    final String star = "star"
    final String of = "of"
    final String on = "on"
    final String that = "that"
    final String off = "off"
    final String sources = "sources"
    final String targets = "targets"
    final String any = "any"
    final String ping_list = "ping_list"
    final String measurement_list = "measurement_list"
    final String periodic = "periodic"
}

